spring:
  datasource:
    username:
    password:
    url: "jdbc:postgresql://localhost:5432/elderest"
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


#  security:
#    user:
#      name: "admin"
#      password: "puc2021"
